export const about = {
  tag: 'main',
  text: '',
  attributes: {},
  classes: 'chat',
  child: [
    {
      tag: 'section',
      text: '',
      attributes: {},
      classes: 'chat-header',
      child: [
        {
          tag: 'label',
          text: 'Пользователь: Myname',
          attributes: { identifier: 'user-info' },
          classes: 'chat-header-user-name',
          child: [],
        },
        { tag: 'label', text: 'Fun Chat', attributes: {}, classes: 'chat-header-app-name', child: [] },
        {
          tag: 'div',
          text: '',
          attributes: {},
          classes: 'chat-header-buttons',
          child: [
            {
              tag: 'button',
              text: 'Выход',
              attributes: { type: 'button', identifier: 'chat-logout' },
              classes: 'chat-header-buttons-logout',
              child: [],
            },
            {
              tag: 'button',
              text: 'i',
              attributes: { type: 'button', identifier: 'chat-info' },
              classes: 'chat-header-buttons-info',
              child: [],
            },
          ],
        },
      ],
    },
    {
      tag: 'section',
      text: '',
      attributes: {},
      classes: 'chat-main',
      child: [
        {
          tag: 'div',
          text: '',
          attributes: {},
          classes: 'chat-main-left',
          child: [
            {
              tag: 'input',
              text: '',
              attributes: { placeholder: 'Поиск...', identifier: 'left-search' },
              classes: 'chat-main-left-search',
              child: [],
            },
            {
              tag: 'ul',
              text: '',
              attributes: { identifier: 'left-users-list' },
              classes: 'chat-main-left-users-list',
              child: [
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: { identifier: 'left-users-status' },
                      classes: 'chat-main-left-users-list-user-status user-status-active',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'zxcv1',
                      attributes: { identifier: 'left-users-login' },
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status user-status-active',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Petr1995',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status user-status-active',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'zxcv2',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status user-status-active',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Wwwww',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status user-status-active',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Qqqqq',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status user-status-active',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Ellie',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status user-status-active',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Asdff',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Lumba',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'sdcl,sdc',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'jhkjh',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Igar1',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Qwertyu',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Karll',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Somecd',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Annaa',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'nicealx',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Demofg',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Derrr',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'lkmkm',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'fffff',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Bobbb',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'cyberax',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Aaaaa',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'rredq',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'kokoko',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Dfsdfs',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Qqqqqq',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'qqqqqqSS',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Asdfg',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Cathrine',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Maryam',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'gtrhgrt',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Я устал босс',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Valeriy',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'sdfbgv',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'kjgskjg',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Molestiae',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Asdasdas',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Wwwww',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Ирина',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Assss',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'irakli',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Yuliya10',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Sssss',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Qqqqq',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'aaaaa',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'uuuuu',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Exercitationem\n                aute',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: '222Qwe',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Admin',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
                {
                  tag: 'li',
                  text: '',
                  attributes: {},
                  classes: 'chat-main-left-users-list-user',
                  child: [
                    {
                      tag: 'div',
                      text: '',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-status',
                      child: [],
                    },
                    {
                      tag: 'label',
                      text: 'Serge',
                      attributes: {},
                      classes: 'chat-main-left-users-list-user-login',
                      child: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          tag: 'div',
          text: '',
          attributes: {},
          classes: 'chat-main-right',
          child: [
            {
              tag: 'div',
              text: '',
              attributes: {},
              classes: 'chat-main-right-companion',
              child: [
                {
                  tag: 'div',
                  text: '',
                  attributes: { identifier: 'right-companion-login' },
                  classes: 'chat-main-right-companion-login',
                  child: [],
                },
                {
                  tag: 'div',
                  text: '',
                  attributes: { identifier: 'right-companion-status' },
                  classes: 'chat-main-right-companion-status',
                  child: [],
                },
              ],
            },
            {
              tag: 'div',
              text: '',
              attributes: { identifier: 'right-dialog' },
              classes: 'chat-main-right-dialog',
              child: [
                {
                  tag: 'label',
                  text: 'Выберите пользователя для отправки сообщения...',
                  attributes: { identifier: 'right-dialog-placeholder' },
                  classes: 'chat-main-right-dialog-placeholder',
                  child: [],
                },
              ],
            },
            {
              tag: 'form',
              text: '',
              attributes: {},
              classes: 'chat-main-right-send',
              child: [
                {
                  tag: 'input',
                  text: '',
                  attributes: { placeholder: 'Сообщение...', disabled: '', value: '', identifier: 'right-send-input' },
                  classes: 'chat-main-right-send-input',
                  child: [],
                },
                {
                  tag: 'button',
                  text: 'Отправить',
                  attributes: { type: 'button', disabled: '', identifier: 'right-send-button' },
                  classes: 'chat-main-right-send-button',
                  child: [],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      tag: 'section',
      text: '',
      attributes: {},
      classes: 'chat-footer',
      child: [
        { tag: 'label', text: 'RSSchool', attributes: {}, classes: '', child: [] },
        { tag: 'label', text: 'CerBeer', attributes: {}, classes: '', child: [] },
        { tag: 'label', text: '2024', attributes: {}, classes: '', child: [] },
      ],
    },
  ],
};
