export const MESSAGES_CHAT_SERVICE_TYPES = {
  UPDATE_COMPANIONS_LIST: 'UPDATE_COMPANIONS_LIST',
  RECEIVING_MESSAGE_FROM_COMPANION: 'RECEIVING_MESSAGE_FROM_COMPANION',
  MESSAGE_HISTORY_WITH_USER: 'MESSAGE_HISTORY_WITH_USER',
  COMPANION_STATUS_UPDATE: 'COMPANION_STATUS_UPDATE',
  RESPONSE_MESSAGE_TO_COMPANION: 'RESPONSE_MESSAGE_TO_COMPANION',
  MESSAGE_DELIVERY_STATUS_CHANGE: 'MESSAGE_DELIVERY_STATUS_CHANGE',
  MESSAGE_READ_STATUS_CHANGE: 'MESSAGE_READ_STATUS_CHANGE',
  MESSAGE_EDITED: 'MESSAGE_EDITED',
  MESSAGE_DELETED: 'MESSAGE_DELETED',
};
